### ISSUE TITLE
Merge proposal with svelte-brunch

### ISSUE THREAD

**Issue by kazzkiq** [StarpTech/sveltejs-brunch#1]
Hello, I'm the maintainer of [svelte-brunch](https://github.com/kazzkiq/svelte-brunch) repo.

Since I have little to no time to keep updating that repo with new configs and Svelte features, I was thinking maybe a good approach would be merging both repos.

The benefits come in both ways: We make the name cleaner (`svelte-brunch` without redundant `js`), avoid confusion (due to two Brunch plugins to choose from), and join efforts working on one plugin.

If you like the idea, I would gladly pass [svelte-brunch](https://github.com/kazzkiq/svelte-brunch) along with npm package ownership to you in order to keep the simpler name, and then turn into a contributor.

What do you think?

**Comment by StarpTech** [comment]
Hi @kazzkiq I like the idea but the benefits are minimal if you have no time to work on it. Almost all features are done. Switching the repo just because a `js` in the name is extra effort which can be saved if you see it in the relation to the popularity of svelte and brunch. I leave this issue open and wait for feedback from the community.
